from sms_ui.call_filter_setting_dialog import open_call_filter_setting_dialog
from sms_ui.keywords_setting_dialog import open_keywords_setting_dialog
from sms_ui.sms_font_dialog import open_sms_font_dialog
