# Generated by tools/sync_firmware_package.py; edit the canonical server parser.
"""Strict, offline script/resource OTA packages for the deployed Air724UG CORE.

The 112-byte, no-change RDAOTA02 section below was produced by OpenLuat's
official 8910 tool with identical old/new COREs. Two independent synthetic
LuaDBs reproduced the complete vendor output byte-for-byte. It contains only
base-image checks, no CORE patch operations. Never generalize it to other COREs.
See script/OTA.md for provenance and the Luatools input requirements.
"""
import hashlib
import io
import json
import re
import struct
import zipfile
import zlib
from dataclasses import dataclass


CORE = "LuatOS-Air_V4029_RDA8910_RFTIPMSTSVT_0x70000"
CORE_SHA256 = "e528095a1f8fb3236a596c95ac5f10c80fb2405e953b729be4112fd014d23676"
PROJECT = "air724ug-forwarder"
CAPACITY = 0x70000
MAGIC = b"AIR724SMS-OTA1\n"
MAX_PACKAGE_BYTES = CAPACITY + 16384
LUA_MAGIC = struct.pack("<I", 2774181210)
LUA_HEADER = bytes.fromhex("1b4c75615100010404040800")
CORE_CHECK = bytes.fromhex(
    "5244414f54413032700000004b13346870000000000000000200000002000000"
    "0000000003000000180000002f6d6f64656d6e766d2f7374617469635f6e762e"
    "62696e00cc0500008dc54f3003000000140000002f6d6f64656d6e766d2f7266"
    "5f6e762e62696e0000580000b6ed30b9"
)
NATIVE_PREFIX = b"\x7e\0\0\0\2\x7d" + struct.pack(">I", len(CORE_CHECK)) + CORE_CHECK + b"\x7c"
CRC_FILE = ".airm2m_all_crc#.bin"
REQUIRED_LUA = {
    "main", "config", "util_ota", "util_config", "util_config_schema",
    "handler_call", "handler_sms", "handler_powerkey", "util_websocket",
    "util_mobile", "util_notify", "util_http", "util_ntp", "util_audio",
    "util_temperature", "usbmsc", "sys", "log", "cc", "sms", "ril", "nvm",
    "audio", "record", "misc", "net", "sim", "pm", "powerKey", "pins",
    "netLed", "common", "utils", "clib", "patch", "link", "socket",
    "socket4G", "websocket", "http", "ntp",
}
REQUIRED_AUDIO = {
    "audio_ring.mp3", "audio_new_sms.mp3", "audio_http_success.mp3",
    "audio_pickup_record.amr", "audio_pickup_hangup.amr",
}


class PackageError(ValueError):
    """A fixed, user-facing error; never include file contents or config values."""


def version_tuple(value):
    if not isinstance(value, str) or not re.fullmatch(r"\d{1,4}\.\d{1,4}\.\d{1,4}", value):
        raise PackageError("固件版本必须为 X.Y.Z")
    return tuple(map(int, value.split(".")))


class _LuaChunk:
    """Read Lua 5.1 float bytecode without evaluating any code or constants."""

    def __init__(self, data):
        self.data, self.pos = data, 0

    def read(self, size):
        if size < 0 or self.pos + size > len(self.data):
            raise PackageError("Lua 字节码长度不正确")
        value = self.data[self.pos:self.pos + size]
        self.pos += size
        return value

    def uint(self):
        return struct.unpack("<I", self.read(4))[0]

    def string(self):
        size = self.uint()
        if not size:
            return None
        value = self.read(size)
        if value[-1:] != b"\0":
            raise PackageError("Lua 字节码字符串损坏")
        return value[:-1]

    def function(self, depth=0):
        if depth > 64:
            raise PackageError("Lua 字节码嵌套过深")
        self.string()
        self.read(12)  # Lines and register/parameter signature.
        instructions = self.read(self.uint() * 4)
        constants = []
        count = self.uint()
        if count > len(self.data):
            raise PackageError("Lua 字节码常量表损坏")
        for _ in range(count):
            kind = self.read(1)[0]
            if kind == 0:
                value = None
            elif kind == 1:
                value = self.read(1)
            elif kind == 3:
                value = self.read(8)
            elif kind == 4:
                value = self.string()
            else:
                raise PackageError("Lua 字节码常量类型不正确")
            constants.append(value if kind == 4 else None)
        children = self.uint()
        if children > len(self.data) // 12:
            raise PackageError("Lua 字节码函数表损坏")
        for _ in range(children):
            self.function(depth + 1)
        self.read(self.uint() * 4)
        locals_count = self.uint()
        if locals_count > len(self.data) // 12:
            raise PackageError("Lua 调试信息损坏")
        for _ in range(locals_count):
            self.string()
            self.read(8)
        upvalues = self.uint()
        if upvalues > len(self.data) // 4:
            raise PackageError("Lua 调试信息损坏")
        for _ in range(upvalues):
            self.string()
        return instructions, constants

    def identity(self):
        if self.read(12) != LUA_HEADER:
            raise PackageError("请使用 Luatools 普通脚本编译；不支持源码或密码加密包")
        instructions, constants = self.function()
        if self.pos != len(self.data):
            raise PackageError("Lua 字节码存在多余数据")
        values, registers = {}, {}
        # PROJECT/VERSION are literal assignments at the beginning of main.lua.
        for (word,) in struct.iter_unpack("<I", instructions[:128]):
            opcode, reg, index = word & 63, (word >> 6) & 255, word >> 14
            if opcode == 1 and index < len(constants):  # LOADK
                registers[reg] = constants[index]
            elif opcode == 7 and index < len(constants):  # SETGLOBAL
                key = constants[index]
                if key in (b"PROJECT", b"VERSION"):
                    value = registers.get(reg)
                    if not isinstance(value, bytes) or key in values:
                        raise PackageError("入口项目名称或版本无法可靠识别")
                    values[key] = value
            else:
                registers.clear()
        return values


def _tlv(data, pos):
    start, fields = pos, {}
    while pos + 2 <= len(data):
        key, size = data[pos:pos + 2]
        pos += 2
        value = data[pos:pos + size]
        if len(value) != size or key in fields:
            break
        if key == 254:
            if size != 2 or int.from_bytes(value, "little") != sum(data[start:pos]) & 65535:
                break
            return fields, pos + size
        fields[key] = value
        pos += size
    raise PackageError("LuaDB 文件头或校验损坏")


def inspect_luadb(data):
    if not 24 <= len(data) <= CAPACITY:
        raise PackageError("脚本和资源超出当前 CORE 的 458752 字节容量")
    head, pos = _tlv(data, 0)
    if (head.get(1), head.get(2), head.get(3)) != (LUA_MAGIC, b"\2\0", b"\x18\0\0\0") or len(head.get(4, b"")) != 2:
        raise PackageError("只支持 Luatools LuaDB v2 编译包")
    count = int.from_bytes(head[4], "little")
    if not 1 <= count <= 128:
        raise PackageError("升级包文件数量不正确")
    files, names = {}, set()
    for index in range(count):
        fields, pos = _tlv(data, pos)
        try:
            name = fields[2].decode("ascii")
        except (KeyError, UnicodeError):
            raise PackageError("升级包文件名不正确") from None
        if fields.get(1) != LUA_MAGIC or len(fields.get(3, b"")) != 4 or name.lower() in names:
            raise PackageError("升级包文件头或重复文件名不正确")
        names.add(name.lower())
        size = int.from_bytes(fields[3], "little")
        body = data[pos:pos + size]
        if len(body) != size:
            raise PackageError("升级包文件内容不完整")
        if name == CRC_FILE:
            if index != count - 1 or size != 16 or body != hashlib.md5(data[:pos]).digest():
                raise PackageError("LuaDB 完整性校验失败")
        elif re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*\.luac", name):
            _LuaChunk(body).identity()
        elif name in REQUIRED_AUDIO:
            if not body:
                raise PackageError("音频资源为空")
        elif name != "amcfg.ini":
            raise PackageError("升级包包含不支持的文件类型")
        files[name] = body
        pos += size
    required = {name + ".luac" for name in REQUIRED_LUA} | REQUIRED_AUDIO | {CRC_FILE, "amcfg.ini"}
    if pos != len(data) or not required.issubset(files):
        raise PackageError("升级包不完整：须包含现行全部模块、OTA 模块和五个音频资源")
    identity = _LuaChunk(files["main.luac"]).identity()
    try:
        project, version = identity[b"PROJECT"].decode("ascii"), identity[b"VERSION"].decode("ascii")
    except (KeyError, UnicodeError):
        raise PackageError("无法识别固件项目和版本") from None
    if project != PROJECT:
        raise PackageError("升级包不是本项目固件")
    version_tuple(version)
    return {
        "project": project, "version": version, "core": CORE,
        "core_sha256": CORE_SHA256, "format": 1, "capacity": CAPACITY,
        "lua_bytes": len(data), "files": len(files), "mode": "luac-float-no-password",
        "config_md5": hashlib.md5(files["config.luac"]).hexdigest(),
        "main_md5": hashlib.md5(files["main.luac"]).hexdigest(),
    }


def native_payload(luadb):
    return NATIVE_PREFIX + struct.pack(">I", len(luadb)) + luadb


def build_package(luadb):
    manifest = inspect_luadb(luadb)
    payload = native_payload(luadb)
    manifest.update(size=len(payload), sha256=hashlib.sha256(payload).hexdigest(), md5=hashlib.md5(payload).hexdigest())
    encoded = json.dumps(manifest, sort_keys=True, separators=(",", ":")).encode("ascii")
    return MAGIC + struct.pack(">I", len(encoded)) + encoded + payload


@dataclass(frozen=True)
class FirmwarePackage:
    manifest: dict
    payload: bytes


def parse_package(data):
    if len(data) > MAX_PACKAGE_BYTES or not data.startswith(MAGIC) or len(data) < len(MAGIC) + 4:
        raise PackageError("请选择本项目打包工具生成的 .air724ota 文件")
    offset = len(MAGIC) + 4
    size = int.from_bytes(data[len(MAGIC):offset], "big")
    if not 1 <= size <= 8192 or offset + size > len(data):
        raise PackageError("升级包清单长度不正确")
    try:
        manifest = json.loads(data[offset:offset + size])
    except (ValueError, UnicodeError, RecursionError):
        raise PackageError("升级包清单损坏") from None
    payload = data[offset + size:]
    prefix_length = len(NATIVE_PREFIX)
    if not payload.startswith(NATIVE_PREFIX) or len(payload) < prefix_length + 4:
        raise PackageError("升级包含 CORE 修改或不支持的原生封装")
    luadb = payload[prefix_length + 4:]
    if len(luadb) != int.from_bytes(payload[prefix_length:prefix_length + 4], "big"):
        raise PackageError("原生升级包长度不正确")
    expected = inspect_luadb(luadb)
    expected.update(size=len(payload), sha256=hashlib.sha256(payload).hexdigest(), md5=hashlib.md5(payload).hexdigest())
    if manifest != expected:
        raise PackageError("升级包清单与实际脚本、版本或校验值不一致")
    return FirmwarePackage(expected, payload)


def parse_upload_package(data):
    """Normalize a web upload without trusting its filename or ZIP metadata."""
    if not 1 <= len(data) <= MAX_PACKAGE_BYTES:
        raise PackageError("升级包为空或超过 464 KiB")
    if data.startswith(MAGIC):
        return parse_package(data)
    if not data.startswith(b"PK\x03\x04"):
        raise PackageError("请选择 Luatools 生成的 .dfota.bin 或本项目的 .air724ota 文件")
    try:
        with zipfile.ZipFile(io.BytesIO(data)) as archive:
            entries = archive.infolist()
            # Web uploads only accept the script/resource archive, never a
            # factory PAC, CORE patch, nested path or extra archive member.
            if len(entries) != 1 or entries[0].orig_filename != "app.bin":
                raise PackageError("只支持仅含 app.bin 的 Luatools .dfota.bin 脚本资源包")
            app = entries[0]
            if app.flag_bits & (1 | 64) or app.compress_type not in (zipfile.ZIP_STORED, zipfile.ZIP_DEFLATED):
                raise PackageError("升级包使用了不支持的压缩或密码加密方式")
            if not 1 <= app.file_size <= CAPACITY:
                raise PackageError("脚本和资源超出当前 CORE 的 458752 字节容量")
            # ZipFile verifies the local header, member name and overlap bounds.
            # Its reader can truncate at an untrusted file_size, so inflate the
            # compressed bytes ourselves with a hard output limit and EOF check.
            with archive.open(app):
                name_size, extra_size = struct.unpack_from("<HH", data, app.header_offset + 26)
                offset = app.header_offset + 30 + name_size + extra_size
                compressed = data[offset:offset + app.compress_size]
            if len(compressed) != app.compress_size:
                raise PackageError("Luatools 升级包压缩数据不完整")
            if app.compress_type == zipfile.ZIP_DEFLATED:
                decoder = zlib.decompressobj(-zlib.MAX_WBITS)
                luadb = decoder.decompress(compressed, CAPACITY + 1)
                if not decoder.eof or decoder.unconsumed_tail or decoder.unused_data:
                    raise PackageError("Luatools 升级包压缩数据不完整、含多余数据或超出容量")
            else:
                luadb = compressed
            if len(luadb) != app.file_size or len(luadb) > CAPACITY:
                raise PackageError("Luatools 升级包解压长度不正确")
            if zlib.crc32(luadb) != app.CRC:
                raise PackageError("Luatools 升级包完整性校验失败")
        # Reuse the same LuaDB, bytecode and native-payload validation as the
        # optional offline builder. The ZIP itself is never sent to FOTA.
        return parse_package(build_package(luadb))
    except PackageError:
        raise
    except (zipfile.BadZipFile, RuntimeError, OSError, EOFError, ValueError, NotImplementedError, struct.error, zlib.error):
        raise PackageError("无法读取 Luatools 升级包，文件可能损坏") from None


def read_luatools_app(source):
    """Accept a script-only Luatools source archive, or its merged app.bin."""
    if source.startswith(b"PK"):
        try:
            with zipfile.ZipFile(io.BytesIO(source)) as archive:
                entries = archive.infolist()
                apps = [item for item in entries if item.filename == "app.bin"]
                if len(entries) > 8 or len(apps) != 1 or apps[0].file_size > CAPACITY or apps[0].flag_bits & 1:
                    raise PackageError("Luatools 源包必须包含唯一且未加密的 app.bin")
                return archive.read(apps[0])
        except (zipfile.BadZipFile, RuntimeError, OSError):
            raise PackageError("无法读取 Luatools 源包") from None
    return source
