"""Bundle the canonical server parser for standalone desktop installations."""
import argparse
from pathlib import Path

HEADER = "# Generated by tools/sync_firmware_package.py; edit the canonical server parser.\n"
CLIENT = Path(__file__).resolve().parents[1]
SOURCE = CLIENT.parents[1] / "air724ug-sms-server/server_modules/server_firmware_package.py"
TARGET = CLIENT / "sms/sms_core/firmware_package.py"


def sync(check=False):
    expected = HEADER + SOURCE.read_text(encoding="utf-8-sig")
    if check:
        return TARGET.is_file() and TARGET.read_text(encoding="utf-8-sig") == expected
    TARGET.write_text(expected, encoding="utf-8")
    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if not sync(args.check):
        parser.exit(1, "Desktop firmware parser is stale; run tools/sync_firmware_package.py\n")
    print("Desktop firmware parser matches the canonical server parser")
